apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  namespace: pixelforge
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::266735805454:role/pixelforge-dev-api

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker
  namespace: pixelforge
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::266735805454:role/pixelforge-dev-worker

