#lightweight debian builder image
FROM python:3.12-slim AS builder 

WORKDIR /build

#create virtual environment
RUN python -m venv /opt/venv

#prepend to path
ENV PATH="/opt/venv/bin:$PATH"

#copy our requirements to /build/requirements/
COPY requirements/api.txt ./requirements/api.txt

#install dependencies to venv 
RUN pip install --no-cache-dir -r requirements/api.txt



FROM python:3.12-slim AS runtime

ENV PATH="/opt/venv/bin:$PATH" \
    TMPDIR=/tmp

#create nonroot group+user 
RUN groupadd --gid 10001 pixelforge \
 && useradd --uid 10001 --gid 10001 --no-create-home --shell /usr/sbin/nologin pixelforge

#copy installed packages
COPY --from=builder /opt/venv /opt/venv

WORKDIR /app
COPY shared/ ./shared/
COPY api/ ./api/

#switch to nonroot user
USER 10001:10001

EXPOSE 8000
STOPSIGNAL SIGTERM

ENTRYPOINT ["python", "-m", "api.main"]
