#lightweight python as builder
FROM python:3.12-slim AS builder

#working directory
WORKDIR /build

#creating virtual environment
RUN python -m venv /opt/venv

#setting our venv to main path
ENV PATH="/opt/venv/bin:$PATH"

COPY requirements/worker.txt ./requirements/worker.txt

#install packages without cache
RUN pip install --no-cache-dir -r requirements/worker.txt




FROM python:3.12-slim AS runtime


ENV PATH="/opt/venv/bin:$PATH" \
    TMPDIR=/tmp

RUN groupadd --gid 10001 pixelforge \
 && useradd --uid 10001 --gid 10001 --no-create-home --shell /usr/sbin/nologin pixelforge

COPY --from=builder /opt/venv /opt/venv

WORKDIR /app
COPY shared/ ./shared/
COPY worker/ ./worker/

USER 10001:10001

EXPOSE 9090
STOPSIGNAL SIGTERM

ENTRYPOINT ["python", "-m", "worker.main"]
