apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml #namespace first
  - configmap.yaml 
  - serviceaccounts.yaml
  - api-deployment.yaml
  - worker-deployment.yaml
  - api-hpa.yaml
  - autoscaling.yaml
  - alerts.yaml
  - dashboard.yaml
  - monitors.yaml
