apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#use the base kustomization
resources:
  - ../../base  

namespace: pixelforge

#image amendments
images:
  - name: pixelforge-api 
    #new image (repo + tag)
    newName: 266735805454.dkr.ecr.eu-west-2.amazonaws.com/pixelforge/api
    newTag: 33165c94d91a86ec4fee60d12ddaa2454d4b3e01

  - name: pixelforge-worker 
    #new image (repo + tag)
    newName: 266735805454.dkr.ecr.eu-west-2.amazonaws.com/pixelforge/worker
    newTag: 33165c94d91a86ec4fee60d12ddaa2454d4b3e01
    
