apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#use the base kustomization
resources:
  - ../../base  

namespace: pixelforge

#image amendments
images:
  - name: pixelforge-api 
    #new image (repo + tag)
    newName: 266735805454.dkr.ecr.eu-west-2.amazonaws.com/pixelforge/api
    newTag: e25d560c2aaba61f96be65b34e23df30431854bc

  - name: pixelforge-worker 
    #new image (repo + tag)
    newName: 266735805454.dkr.ecr.eu-west-2.amazonaws.com/pixelforge/worker
    newTag: e25d560c2aaba61f96be65b34e23df30431854bc
    
