name: TF-Platform-Apply

on:
  workflow_dispatch:
    inputs:
      action:
        description: "apply or plan"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply

env:
  AWS_REGION: eu-west-2
  TF_VAR_pixelforge_ci_role: ${{ secrets.AWS_CI_ROLE_ARN }}

concurrency:
    group: tf-platform-apply-${{ github.ref }}
    cancel-in-progress: false

jobs:
  tfDeploy:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: terraform/platform

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v7
      - uses: hashicorp/setup-terraform@v4
      - uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_CI_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: tf format
        run: terraform fmt -check
        continue-on-error: true

      - name: tf init
        run: terraform init -input=false

      - name: tf validate
        run: terraform validate 

      - name: tf plan
        run: terraform plan -input=false -out=tfplan

      - name: tf apply
        if: ${{ inputs.action == 'apply' }}
        run: terraform apply -input=false tfplan
