#name of our workflow
name: ci

#our triggers (pushes to main & PRs)
on:
  push:
    branches: [main]
  pull_request:

#concurrency of workflows
concurrency:
  group: ci-${{ github.ref }}

  #cancel the older run
  cancel-in-progress: true

permissions:
  contents: read


env:
  AWS_REGION: eu-west-2

jobs:
  #halt on failed python tests
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.12"
          #cache key
          cache: pip
      - run: pip install -r requirements/dev.txt
      - run: pytest -q  
  
  #halt on failed terraform validation
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v4
      - run: terraform fmt -check -recursive
        working-directory: terraform
      - run: terraform init -backend=false
        working-directory: terraform
      - run: terraform validate
        working-directory: terraform
  
  #build and push docker images
  #scanned by trivy for high/crit vulnerabilities 
  build:
    #depends on the above two
    needs: [test,terraform]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    #run both jobs in parallel
    strategy:
      matrix:
        service: [api,worker]


    steps:
      - uses: actions/checkout@v4
      
      - uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          severity: HIGH,CRITICAL
          exit-code: "1"

        #OIDC Exchange
      - uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_CI_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - id: ecr
        uses: aws-actions/amazon-ecr-login@v2

        #pushing each service's image
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/DockerFile.$${{ matrix.service }}
          
          #push circumstances
          push: ${{ github.event_name != 'pull_request' }}

          #image tag
          tags: ${{ steps.ecr.outputs.registry }}/pixelforge/${{ matrix.service }}:${{ github.sha }}

          cache-from: type=gha
          cache-to: type=gha, mode=max

